### PR TITLE
Pricing page mobile

### PR DESCRIPTION
**Pull request by Cdaoustd**
Hey guys! 

So here is a first try for the mobile version. I tried following some of the designs from the pdf (eg: adding little lines between certain prices) but in other places I just stayed as close to the desktop design as possible (eg: the networking table). My reasonning behind leaving the networking table as it was is that it would have made the mobile page even longer if I followed the design and I was starting to find that page very heavy for a mobile page.

I still don't know if there is a decision made for the design of the page navigation (grey and white navbars)so so far, I have left them alone. I can try something based on past conversations and show you for approval, if you would like.

Also, I am well aware that the page is not at all functional in the "tablet" sizes, I will be waiting for the approval of the mobile design to proceed with this one, if you agree?

Tell me what you think!

### CODE REVIEW

**Comment by swill** [comment]
I suggest we use the `mobile` version for the tablet layout as well.

Between the width of 991px and 769px wide, we get a strange broken UI before it is small enough for the mobile theme to take over.  I suspect you will want to change your media queries to manage the changes in layout.

image

**Comment by swill** [comment]
I have seen that this happens often at different screen sizes.  It looks like this is related to if the line wraps or not in the cell.

I think we probably want to use something like a `min-height` on this to manage the height of the cells.

image

**Comment by Cdaoustd** [comment]
yes, i just noticed that last night. I was thinking about using
white-space: nowrap

Min-size would probably work as well :) Ill try that, thanks

**Comment by Cdaoustd** [comment]
Yeah, its a bootstrap thing that happens because Ive been working with
their screen sizes, mentionning the prefered layout for large screens and
small ones but skipping the medium size so far. I just wanted to get your
feedback on the mobile design before making it work on medium size as well
:)

**Comment by swill** [comment]
Also, overlapping text at some screen sizes.

image

**Comment by Cdaoustd** [comment]
Yeah, I probably did something wrong there, Ive never seen that before 🙈

**Comment by swill** [comment]
Most of the issues I noticed before seem to be fixed.

I forgot to mention this one, but there seems to be a regression in the menu overlay (mouse over in desktop and in mobile view).

The background should not go to such a dark grey, it should match the footer gradient.  Very small amount of transition.

image

**Comment by Cdaoustd** [comment]
Alright, I fixed it :)

Le mar. 2 oct. 2018, à 10 h 57, Will Stevens <notifications@github.com> a
écrit :

**Comment by swill** [comment]
I think all of the major items are accounted for with this PR now.  I am merging.  Sorry for the delay...

**Comment by Cdaoustd** [comment]
No problem. I will be able to consacrate all of my attention to this
project within a few weeks so let me know whenever you are ready for the
next phase!

Have a good night!

Carine

**Pull request merged**
