### PR TITLE
Pricing page basic template

### PR DESCRIPTION
**Pull request by Cdaoustd**
This pull request title is missleading, it is actually because I finished the homepage. I am still working on the rest.

I tried adding Khosrow to this but I did not manage.

Thank you

### CODE REVIEW

**Comment by khos2ow** [comment]
hmm, are you sure it works? At first I was getting an error which I found that `title-card.html` was in `layouts/partials/Pricing` where the other files were in `layouts/partials/pricing` (lowercase `p`).

After I moved the file, it worked but it seems the layout is messed up (or I'm missing something, and haven't investigated further)

@swill I think we need to setup a Travis + Netlify setup asap to generate each PR's to have more accessible and easier way to validate PRs.

**Comment by Cdaoustd** [comment]
You are right, I noticed the pricing issue right after and forgot to aubmit
my changes to github. Sorry...

As for the layout? Are you looking at the secondary page? Because that one
is not finished so it’s normal that it doesn’t all work. I sent for this
pull request only for the homepage, because that page is completed

Hope this helps,

Carine

**Comment by swill** [comment]
I fixed the issue with the track file where the case was incorrect for the `Pricing` partial folder.

I will merge this and I will open issues for things I would like to get in the backlog.  I won't focus on things on the `pricing` page as I know that is a work in progress.

**Comment by swill** [comment]
@khos2ow yes, I would like to setup some form of CI on this.  I have some ideas, but am interested in your ideas as well.  Maybe we can sync up and figure out what would make the most sense?

**Comment by khos2ow** [comment]
@swill sure, that'd be great. May be we can have a quick discussion during/after lunch today?

**Pull request merged**
